// src/components/ProjectCard.jsx
// src/components/ProjectCard.jsx
import React from "react";
import { useDraggable } from "@dnd-kit/core";

export function ProjectCard({ id, title, url }) {
  const { attributes, listeners, setNodeRef, transform } = useDraggable({ id });

  const style = {
    transform: transform ? `translate3d(${transform.x}px, ${transform.y}px, 0)` : undefined,
  };

  return (
    <a
      href={url}
      target="_blank"
      rel="noopener noreferrer"
      ref={setNodeRef}
      style={style}
      {...listeners}
      {...attributes}
      className="block bg-blue-100 hover:bg-blue-200 p-3 rounded-lg shadow mb-2 cursor-move"
    >
      {title}
    </a>
  );
}

// svelte/src/components/ProjectCard.svelte
<!-- src/components/ProjectCard.svelte -->
<script>
  export let project;
</script>

<div class="p-2 text-left bg-white rounded border shadow-sm cursor-move" data-id={project.id}>
  <a href={project.url} target="_blank" class="hover:underline text-blue-600">
    {project.title}
  </a>
  <div class="mt-0.5 text-xs text-gray-400">{project.id}</div>
</div>
